# Generated by Django 2.0.1 on 2018-01-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocess', '0002_preprocessdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprocessdetail',
            name='preprocess_id',
            field=models.IntegerField(),
        ),
    ]
