# Generated by Django 2.0 on 2017-12-26 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bills',
            options={'ordering': ('created', 'owner')},
        ),
    ]
